apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: fullstack-app
type: Opaque
stringData:
  NODE_ENV: "development"
  PORT: "4000"
  SECRET: "hackthoon"
  KEY: "idurar"
  JWT_SCHEME: "jwt"
  JWT_TOKEN_PREFIX: "Bearer"
  JWT_SECRET: "thiscanbechangedlater123654789"
  JWT_TOKEN_EXPIRATION: "18000000"
  JWT_TOKEN_HASH_ALGO: "SHA-256"