apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backendsecret.name }}
  namespace: {{ .Values.namespace }}
type: {{ .Values.backendsecret.type }}
stringData:
  {{- range $key, $value := .Values.backendsecret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}