{{- $name := .Values.mongo-statefulset.name }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ $name }}
  replicas: {{ .Values.mongo-statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
      - name: {{ $name }}
        image: {{ .Values.mongo-statefulset.container.image }}
        ports:
        - containerPort: 27017
          name: {{ $name }}
        resources:
          requests:
            cpu: {{ .Values.mongo-statefulset.resources.requests.cpu }}
            memory: {{ .Values.mongo-statefulset.resources.requests.memory }}
          limits:
            cpu: {{ .Values.mongo-statefulset.resources.limits.cpu }}
            memory: {{ .Values.mongo-statefulset.resources.limits.memory }}
        volumeMounts:
        - name: {{ .Values.mongo-statefulset.volumeMounts.name }}
          mountPath: {{ .Values.mongo-statefulset.volumeMounts.mountPath }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.mongo-statefulset.volumeMounts.name }}
    spec:
      accessModes: {{ .Values.mongo-statefulset.spec.accessModes }}
      storageClassName: {{ .Values.mongo-statefulset.spec.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.mongo-statefulset.storage.size }}