apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo-secret.name }}
  namespace: {{ .Values.namespace }}
type: {{ .Values.mongo-secret.type }}
stringData:
  MONGO_URL: {{ .Values.mongo-secret.data.MONGO_URL }}
  MONGO_DB: {{ .Values.mongo-secret.data.MONGO_DB }}