apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx-loadbalancer.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.nginx-loadbalancer.selector.app }}
  ports:
  - protocol: {{ .Values.nginx-loadbalancer.spec.protocol }}
    port: {{ .Values.nginx-loadbalancer.spec.port }}
    targetPort: {{ .Values.nginx-loadbalancer.spec.targetPort }}
  type: {{ .Values.nginx-loadbalancer.spec.type }}