services:
  mongo:
    image: mongo:5
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: prem1112223/dockerizedbackend:v3.2
    env_file:
      - ./backend/.variables.env
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://backend-service.fullstack-app.svc.cluster.local:4000/api/
    image: prem1112223/dockerizedfrontend:v3.2
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
