services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: prodcontainer.azurecr.io/backend:v4.0
    ports:
      - "4000:4000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: prodcontainer.azurecr.io/backend:v4.0
    ports:
      - "3000:80"

# :) :)
