services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: prem1112223/dockerizedbackend:v4.0
    ports:
      - "4000:4000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: prem1112223/dockerizedfrontend:v4.0
    ports:
      - "3000:80"