namespace: default

backend-deployment:
  name: backend-service
  replicaCount: 1
  image:
    repository: prodcontainer.azurecr.io/backend
    tag: latest
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 200m
      memory: 500Mi
  secretName:
    mongo: mongo-secret
    backend: backend-secret
  volumes:
    name: secrets-store-inline
    driver: secrets-store.csi.k8s.io
    readOnly: true
    secretProviderClass: "fullstack-secrets"
    mountPath: /mnt/secrets-store

backend-service:
  name: backend-service
  spec:
    port: 4000
    targetPort: 4000
    protocol: TCP
    name: http
    type: ClusterIP

frontend-deployment:
  name: frontend
  replicaCount: 1
  image:
    repository: prodcontainer.azurecr.io/frontend
    tag: latest
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 200m
      memory: 500Mi
  secretName:
    frontend: frontend-secret

frontend-service:
  name: frontend-service
  selector:
    app: frontend
  spec:
    port: 80
    targetPort: 80

mongo-service:
  name: mongo
  spec:
    port: 27017

mongo-statefulset:
  name: mongo
  replicas: 1
  container:
    image: mongo:5
  storage:
    size: 5Gi
    storageClassName: managed-premium
  volumeMounts:
    mountPath: /data/db
    name: mongo-storage
  resources:
    requests:
      cpu: 200m
      memory: 500Mi
    limits:
      cpu: 500m
      memory: 1Gi
  spec:
    accessModes:
      - ReadWriteOnce
    storageClassName: managed-premium

nginx-configmap:
  name: nginx-config
  data:
    nginxconf: |-
      server {
          listen 80;

          location / {
              proxy_pass http://frontend-service.default.svc.cluster.local:80;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }

          location /api/ {
            proxy_pass http://backend-service.default.svc.cluster.local:4000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
      }

nginx-deployment:
  name: nginx-proxy
  replicas: 1
  image: nginx:alpine
  resources:
    name: nginx
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi
  volumeMounts:
    mountPath: /etc/nginx/conf.d
    name: nginx-config-volume
    subpath: nginx.conf
  ConfigMap:
    name: nginx-config

nginx-loadbalancer:
  name: nginx-proxy
  selector:
    app: nginx-proxy
  spec:
    port: 80
    targetPort: 80
    protocol: TCP
    type: LoadBalancer

secrets:
  secretProviderClass:
    name: fullstack-secrets
    provider: azure
    secretObjects:
      - secretName: mongo-secret
        type: Opaque
        data:
          - objectName: mongo-database-uri
            key: DATABASE
          - objectName: mongo-database-name
            key: MONGO_DB
      - secretName: backend-secret
        type: Opaque
        data:
          - objectName: backend-node-env
            key: NODE_ENV
          - objectName: backend-port
            key: PORT
          - objectName: backend-secret-key
            key: SECRET
          - objectName: backend-key
            key: KEY
          - objectName: backend-jwt-scheme
            key: JWT_SCHEME
          - objectName: backend-jwt-token-prefix
            key: JWT_TOKEN_PREFIX
          - objectName: backend-jwt-secret
            key: JWT_SECRET
          - objectName: backend-jwt-expiration
            key: JWT_TOKEN_EXPIRATION
          - objectName: backend-jwt-hash
            key: JWT_TOKEN_HASH_ALGO
    parameters:
      useVMManagedIdentity: "true"
      userAssignedIdentityID: ""
      usePodIdentity: "false"
      keyvaultName: ""
      cloudName: ""
      objects: |
        array:
          - objectName: mongo-database-uri
            objectType: secret
          - objectName: mongo-database-name
            objectType: secret
          - objectName: backend-node-env
            objectType: secret
          - objectName: backend-port
            objectType: secret
          - objectName: backend-secret-key
            objectType: secret
          - objectName: backend-key
            objectType: secret
          - objectName: backend-jwt-scheme
            objectType: secret
          - objectName: backend-jwt-token-prefix
            objectType: secret
          - objectName: backend-jwt-secret
            objectType: secret
          - objectName: backend-jwt-expiration
            objectType: secret
          - objectName: backend-jwt-hash
            objectType: secret
      tenantId: ""