name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure using Service Principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}

      - name: Log in to Azure Container Registry
        run: az acr login --name prodcontainer

      - name: Build and push frontend Docker image
        run: |
          cd app/frontend
          IMAGE_TAG=prodcontainer.azurecr.io/frontend:${{ github.sha }}
          docker build . -f Dockerfile -t $IMAGE_TAG
          docker push $IMAGE_TAG

      - name: Build and push backend Docker image
        run: |
          cd app/backend
          IMAGE_TAG=prodcontainer.azurecr.io/backend:${{ github.sha }}
          docker build . -f Dockerfile -t $IMAGE_TAG
          docker push $IMAGE_TAG
