name: Build and Deploy to AKS

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'charts/**'
  workflow_dispatch:

concurrency:
  group: build-and-deploy
  cancel-in-progress: false

env:
  CHART_PATH: "./charts"
  CHART_OVERRIDE_PATH: "./charts/values-prod.yaml"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      app_changed: ${{ steps.filter.outputs.app }}
      charts_changed: ${{ steps.filter.outputs.charts }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            app:
              - 'app/**'
            charts:
              - 'charts/**'

  build:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.app_changed == 'true' || needs.detect-changes.outputs.charts_changed == 'true'
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

      - name: Build and push frontend Docker image
        run: |
          cd app/frontend
          IMAGE_TAG=${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/frontend:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Build and push backend Docker image
        run: |
          cd app/backend
          IMAGE_TAG=${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/backend:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: [detect-changes, build]
    if: needs.detect-changes.outputs.charts_changed == 'true' || needs.detect-changes.outputs.app_changed == 'true'
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubelogin
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      - name: Get K8s context
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --name ${{ secrets.CLUSTER_NAME }}

      - name: Bake Helm chart
        uses: azure/k8s-bake@v2
        with:
          renderEngine: "helm"
          helmChart: ${{ env.CHART_PATH }}
          overrideFiles: ${{ env.CHART_OVERRIDE_PATH }}
          overrides: |
            frontend.image.repository=${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/frontend
            frontend.image.tag=${{ github.sha }}
            backend.image.repository=${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/backend
            backend.image.tag=${{ github.sha }}
          helm-version: "latest"
        id: bake

      - name: Deploy application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: |
            ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/frontend:${{ github.sha }}
            ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/backend:${{ github.sha }}
