name: Terraform workflow

on:
  push:
    branches:
      - main
      - staging
      - dev
    paths:
      - 'infra/**'
      - 'app/**'
      - 'charts/**'
  pull_request:
    branches:
      - main
    paths:
      - 'infra/**'

concurrency:
  group: terraform-${{ github.ref_name }}
  cancel-in-progress: false

env:
  TF_VAR_EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
  TF_VAR_arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  GITHUB_TOKEN: ${{ secrets.TFSEC_GITHUB_TOKEN }}
  # Node.js / Backend Variables
  TF_VAR_NODE_ENV: ${{ secrets.NODE_ENV }}
  TF_VAR_PORT: ${{ secrets.PORT }}
  TF_VAR_SECRET: ${{ secrets.SECRET }}
  TF_VAR_KEY: ${{ secrets.KEY }}
  TF_VAR_JWT_SCHEME: ${{ secrets.JWT_SCHEME }}
  TF_VAR_JWT_TOKEN_PREFIX: ${{ secrets.JWT_TOKEN_PREFIX }}
  TF_VAR_JWT_SECRET: ${{ secrets.JWT_SECRET }}
  TF_VAR_JWT_TOKEN_EXPIRATION: ${{ secrets.JWT_TOKEN_EXPIRATION }}
  TF_VAR_JWT_TOKEN_HASH_ALGO: ${{ secrets.JWT_TOKEN_HASH_ALGO }}

  # MongoDB Variables
  TF_VAR_DATABASE: ${{ secrets.DATABASE }}
  TF_VAR_MONGO_DB: ${{ secrets.MONGO_DB }}

jobs:
  tfsec:
    name: 'Security Scan (tfsec)'
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      TFSEC_GITHUB_TOKEN: ${{ secrets.TFSEC_GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Run tfsec (full scan)
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          github_token: ${{ secrets.TFSEC_GITHUB_TOKEN }}
          working_directory: ./infra

  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: |
          cd ./infra
          terraform init
      
      - name: Terraform Format recursive
        run: |
          cd ./infra
          terraform fmt -check

      - name: Terraform Plan
        run: |
          cd ./infra
          terraform plan -input=false \
          -var "owner_email_address=${{ secrets.EMAIL_ADDRESS }}" \
          -var "NODE_ENV=${{ secrets.NODE_ENV }}" \
          -var "PORT=${{ secrets.PORT }}" \
          -var "SECRET=${{ secrets.SECRET }}" \
          -var "KEY=${{ secrets.KEY }}" \
          -var "JWT_SCHEME=${{ secrets.JWT_SCHEME }}" \
          -var "JWT_TOKEN_PREFIX=${{ secrets.JWT_TOKEN_PREFIX }}" \
          -var "JWT_SECRET=${{ secrets.JWT_SECRET }}" \
          -var "JWT_TOKEN_EXPIRATION=${{ secrets.JWT_TOKEN_EXPIRATION }}" \
          -var "JWT_TOKEN_HASH_ALGO=${{ secrets.JWT_TOKEN_HASH_ALGO }}" \
          -var "DATABASE=${{ secrets.DATABASE }}" \
          -var "MONGO_DB=${{ secrets.MONGO_DB }}"

      - name: Terraform Apply
        if: >
          github.event_name == 'push' &&
          (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging')
        run: |
          cd ./infra
          terraform apply -auto-approve -input=false \
          -var "owner_email_address=${{ secrets.EMAIL_ADDRESS }}" \
          -var "NODE_ENV=${{ secrets.NODE_ENV }}" \
          -var "PORT=${{ secrets.PORT }}" \
          -var "SECRET=${{ secrets.SECRET }}" \
          -var "KEY=${{ secrets.KEY }}" \
          -var "JWT_SCHEME=${{ secrets.JWT_SCHEME }}" \
          -var "JWT_TOKEN_PREFIX=${{ secrets.JWT_TOKEN_PREFIX }}" \
          -var "JWT_SECRET=${{ secrets.JWT_SECRET }}" \
          -var "JWT_TOKEN_EXPIRATION=${{ secrets.JWT_TOKEN_EXPIRATION }}" \
          -var "JWT_TOKEN_HASH_ALGO=${{ secrets.JWT_TOKEN_HASH_ALGO }}" \
          -var "DATABASE=${{ secrets.DATABASE }}" \
          -var "MONGO_DB=${{ secrets.MONGO_DB }}"

      - name: Capture Outputs
        id: tf-outputs
        if: >
          github.event_name == 'push' &&
          (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging')
        run: |
          cd ./infra
          echo "PROD_ACR_NAME=$(terraform output -raw prod_acr)" >> $GITHUB_ENV
          echo "PROD_AKS_NAME=$(terraform output -raw prod_aks_cluster_name)" >> $GITHUB_ENV
          echo "PROD_RG_NAME=$(terraform output -raw prod_resource_group)" >> $GITHUB_ENV
          echo "DEV_ACR_NAME=$(terraform output -raw dev_acr)" >> $GITHUB_ENV
          echo "DEV_AKS_NAME=$(terraform output -raw dev_aks_cluster_name)" >> $GITHUB_ENV
          echo "DEV_RG_NAME=$(terraform output -raw dev_resource_group)" >> $GITHUB_ENV
          echo "STAGING_ACR_NAME=$(terraform output -raw staging_acr)" >> $GITHUB_ENV
          echo "STAGING_AKS_NAME=$(terraform output -raw staging_aks_cluster_name)" >> $GITHUB_ENV
          echo "STAGING_RG_NAME=$(terraform output -raw staging_resource_group)" >> $GITHUB_ENV
          echo "PROD_KEY_VAULT_NAME=$(terraform output -raw prod_key_vault_name)" >> $GITHUB_ENV
          echo "PROD_USER_ASSIGNED_IDENTITY_CLIENT_ID=$(terraform output -raw prod_user_assigned_identity_client_id)" >> $GITHUB_ENV
          echo "TENANT_ID=$(terraform output -raw tenant_id)" >> $GITHUB_ENV

      - name: Install GitHub CLI
        if: >
          github.event_name == 'push' &&
          (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging')
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Save Variables to GitHub
        if: >
          github.event_name == 'push' &&
          (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging')
        run: |
          gh variable set PROD_ACR_NAME --body "$PROD_ACR_NAME"
          gh variable set PROD_AKS_NAME --body "$PROD_AKS_NAME"
          gh variable set PROD_RG_NAME --body "$PROD_RG_NAME"
          gh variable set DEV_ACR_NAME --body "$DEV_ACR_NAME"
          gh variable set DEV_AKS_NAME --body "$DEV_AKS_NAME"
          gh variable set DEV_RG_NAME --body "$DEV_RG_NAME"
          gh variable set STAGING_ACR_NAME --body "$STAGING_ACR_NAME"
          gh variable set STAGING_AKS_NAME --body "$STAGING_AKS_NAME"
          gh variable set STAGING_RG_NAME --body "$STAGING_RG_NAME"
          gh variable set PROD_KEY_VAULT_NAME --body "$PROD_KEY_VAULT_NAME"
          gh variable set PROD_USER_ASSIGNED_IDENTITY_CLIENT_ID --body "$PROD_USER_ASSIGNED_IDENTITY_CLIENT_ID"
          gh variable set TENANT_ID --body "$TENANT_ID"

        env:
          PROD_ACR_NAME: ${{ env.PROD_ACR_NAME }}
          PROD_AKS_NAME: ${{ env.PROD_AKS_NAME }}
          PROD_RG_NAME: ${{ env.PROD_RG_NAME }}
          DEV_ACR_NAME: ${{ env.DEV_ACR_NAME }}
          DEV_AKS_NAME: ${{ env.DEV_AKS_NAME }}
          DEV_RG_NAME: ${{ env.DEV_RG_NAME }}
          STAGING_ACR_NAME: ${{ env.STAGING_ACR_NAME }}
          STAGING_AKS_NAME: ${{ env.STAGING_AKS_NAME }}
          STAGING_RG_NAME: ${{ env.STAGING_RG_NAME }}
          KEY_VAULT_NAME: ${{ env.KEY_VAULT_NAME }}
          user_assigned_identity_client_id: ${{ env.user_assigned_identity_client_id }}
          TENANT_ID: ${{ env.TENANT_ID }}
