name: Build and Deploy to AKS

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'charts/**'
      - 'infra/**'
  workflow_dispatch:

concurrency:
  group: terraform-apply
  cancel-in-progress: true

env:
  CHART_PATH: "./charts"
  CHART_OVERRIDE_PATH: "./charts/values-prod.yaml"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      app_changed: ${{ steps.filter.outputs.app }}
      charts_changed: ${{ steps.filter.outputs.charts }}
      infra_changed: ${{ steps.filter.outputs.infra }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            app:
              - 'app/**'
            charts:
              - 'charts/**'
            infra:
              - 'infra/**'

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    needs: detect-changes
    if: needs.detect-changes.outputs.infra_changed == 'true'

    env:
      TF_VAR_EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      TF_VAR_arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: |
          cd ./infra
          terraform init

      - name: Terraform Format
        run: |
          cd ./infra
          terraform fmt -check

      - name: Terraform Plan
        run: |
          cd ./infra
          terraform plan -input=false \
          -var "owner_email_address=${{ secrets.EMAIL_ADDRESS }}"

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cd ./infra
          terraform apply -auto-approve -input=false \
          -var "owner_email_address=${{ secrets.EMAIL_ADDRESS }}"

      - name: Capture Terraform Outputs
        id: get-outputs
        run: |
          cd ./infra
          echo "acr=$(terraform output -raw prod_acr)" >> $GITHUB_OUTPUT
          echo "rg=$(terraform output -raw prod_aks_cluster_name)" >> $GITHUB_OUTPUT
          echo "aks=$(terraform output -raw prod_resource_group)" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: [detect-changes, terraform]
    if: needs.detect-changes.outputs.app_changed == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Log in to ACR
        run: az acr login --name ${{ needs.terraform.outputs.acr }}
      - name: Build & push frontend image
        run: |
          cd app/frontend
          IMAGE_TAG=${{ needs.terraform.outputs.acr }}.azurecr.io/frontend:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
      - name: Build & push backend image
        run: |
          cd app/backend
          IMAGE_TAG=${{ needs.terraform.outputs.acr }}.azurecr.io/backend:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: [detect-changes, build, terraform]
    if: needs.detect-changes.outputs.charts_changed == 'true' || needs.detect-changes.outputs.app_changed == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up kubelogin
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ needs.terraform.outputs.rg }}
          cluster-name: ${{ needs.terraform.outputs.aks }}
          admin: 'false'
          use-kubelogin: 'true'
      - name: Bake Helm chart
        uses: azure/k8s-bake@v2
        with:
          renderEngine: helm
          helmChart: ${{ env.CHART_PATH }}
          overrideFiles: ${{ env.CHART_OVERRIDE_PATH }}
          overrides: |
            frontend.image.repository=${{ needs.terraform.outputs.acr }}.azurecr.io/frontend
            frontend.image.tag=${{ github.sha }}
            backend.image.repository=${{ needs.terraform.outputs.acr }}.azurecr.io/backend
            backend.image.tag=${{ github.sha }}
          helm-version: latest
        id: bake
      - name: Deploy application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: |
            ${{ needs.terraform.outputs.acr }}.azurecr.io/frontend:${{ github.sha }}
            ${{ needs.terraform.outputs.acr }}.azurecr.io/backend:${{ github.sha }}